sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: coralkita_db
    username: root
    password: 123456

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-ap-southeast-3.aliyuncs.com
    accessKeyId: 1
    accessKeySecret: 1
    bucket: coralkita
